# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://www.worlddoctorsalliance.com"
DefaultContentLanguage  = "en"
title                   = "World Doctors Alliance"
theme                   = "hugo-future-imperfect-slim"
paginate                = 12
pluralizeListTitles     = false
disableLanguages        = []

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "Doctors uniting around the world with integrity and right action."
    author              = "WORLD DOCTORS ALLIANCE"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "WELCOME TO THE WORLD DOCTORS ALLIANCE"
    dynamicTitles       = false
    searchMenu          = true
    shareMenu           = true
    languageMenu        = false

  [params.intro]
    header                = "WORLD DOCTORS ALLIANCE"
    paragraph             = "Uniting around the world with integrity and right action."
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/logo.png"
      shape               = "rectangle"
      width               = "184px"
      alt                 = "WORLD DOCTORS ALLIANCE"

  [params.sidebar]
    about               = "Uniting around the world with integrity and right action."
    postAmount          = 3
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "News"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 2

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-address-card'></i>"
    weight            = 4


  [[menu.main]]
    name              = "Sign up"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    title               = "World Doctors Alliance"
    description         = "Uniting around the world with integrity and right action."
    weight              = 1
      
    [Languages.de]
    LanguageCode        = "de"
    LanguageName        = "Deutsche"
    weight              = 5

   [[Languages.de.menu.main]]
      name              = "Ãœber uns"
      identifier        = "about"
      url               = "/about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.de.menu.main]]
      name              = "Nachrichten"
      identifier        = "blog"
      url               = "/blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.de.menu.main]]
      name              = "Kontakt"
      identifier        = "contact"
      url               = "/contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6
      
  [Languages.es]
    LanguageCode        = "es"
    LanguageName        = "Espanol"
    title               = ""
    description         = "."
    weight              = 2

   [[Languages.es.menu.main]]
      name              = "Sobre"
      identifier        = "about"
      url               = "/about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.es.menu.main]]
      name              = "Noticias"
      identifier        = "blog"
      url               = "/blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.es.menu.main]]
      name              = "Contacto"
      identifier        = "contact"
      url               = "/contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

[social]
  # Coding Communities
  # Email
